# Generated by Django 6.0.6 on 2026-07-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='upi_ref',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('awaiting', 'Awaiting verification'), ('paid', 'Paid'), ('enquiry', 'Enquiry (pay later)'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=12),
        ),
    ]
