# Generated by Django 6.0.3 on 2026-06-19 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=100)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.quality')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.size')),
            ],
            options={
                'unique_together': {('product', 'quality', 'color', 'size')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=4)),
                ('qty', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=120)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
