from decimal import Decimal

from django.test import TestCase

from .models import Order


class OrderWorkflowTests(TestCase):
    def setUp(self):
        self.order = Order.objects.create(full_name="A", phone="9999999999",
                                          shipping_address="X", total=Decimal("1000"))

    def test_order_no_autogenerated(self):
        self.assertTrue(self.order.order_no.startswith("TP"))

    def test_set_status_records_event(self):
        self.order.set_status(Order.Status.CONFIRMED, note="paid")
        self.assertEqual(self.order.status, "confirmed")
        self.assertEqual(self.order.events.count(), 1)

    def test_timeline_marks_progress(self):
        self.order.set_status(Order.Status.SHIPPED)
        tl = self.order.timeline()
        labels_done = [s["label"] for s in tl if s["done"]]
        self.assertIn("Pending", labels_done)
        active = [s["label"] for s in tl if s["active"]]
        self.assertEqual(active, ["Shipped"])

    def test_eway_threshold(self):
        big = Order.objects.create(full_name="B", phone="9", shipping_address="Y",
                                   total=Decimal("60000"))
        self.assertTrue(big.needs_eway)
        self.assertFalse(self.order.needs_eway)
