# Generated by Django 6.0.3 on 2026-06-19 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('channel', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10)),
                ('urgent', models.BooleanField(default=False)),
                ('qty_total', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('urgent_charge', models.IntegerField(default=0)),
                ('gst', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('design', 'In Design'), ('production', 'In Production'), ('qc', 'Quality Check'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('payment_status', models.CharField(choices=[('enquiry', 'Enquiry (unpaid)'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='enquiry', max_length=10)),
                ('wants_mockup', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.color')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.quality')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='teepresso', max_length=20)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('watermarked', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Revision asked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockups', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.size')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ['ts'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='upi', max_length=20)),
                ('status', models.CharField(default='unpaid', max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_count_verified', models.IntegerField(blank=True, null=True)),
                ('qc_result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Passed'), ('fail', 'Failed')], default='pending', max_length=10)),
                ('qc_reprinted', models.IntegerField(default=0)),
                ('invoice_no', models.CharField(blank=True, max_length=40)),
                ('awb', models.CharField(blank=True, max_length=40)),
                ('courier', models.CharField(blank=True, max_length=60)),
                ('eway_required', models.BooleanField(default=False)),
                ('eway_no', models.CharField(blank=True, max_length=40)),
                ('dispatched', models.BooleanField(default=False)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
        ),
    ]
