# Generated by Django 6.0.3 on 2026-06-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='design_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='design_preview',
            field=models.TextField(blank=True),
        ),
    ]
