# Generated by Django 6.0.3 on 2026-06-25 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=160)),
                ('contact_person', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('product_requirement', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('budget', models.CharField(blank=True, max_length=60)),
                ('reference_file', models.FileField(blank=True, null=True, upload_to='quotations/')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal', 'Proposal sent'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=12)),
                ('followup_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
