from decimal import Decimal

from django.test import TestCase

from .models import Category, Product
from .pricing import quote, unit_price_for_qty


class PricingTests(TestCase):
    def test_bulk_slab_discount_increases_with_qty(self):
        self.assertEqual(unit_price_for_qty(100, 1), Decimal("100.00"))
        self.assertEqual(unit_price_for_qty(100, 50), Decimal("90.00"))   # 10% off
        self.assertEqual(unit_price_for_qty(100, 300), Decimal("80.00"))  # 20% off
        self.assertEqual(unit_price_for_qty(100, 1000), Decimal("75.00"))  # 25% off

    def test_quote_breakdown(self):
        q = quote(200, 100)
        self.assertEqual(q["qty"], 100)
        self.assertEqual(q["discount_pct"], 15)
        self.assertEqual(q["unit_price"], 170.0)
        self.assertEqual(q["subtotal"], 17000.0)


class ProductModelTests(TestCase):
    def setUp(self):
        self.cat = Category.objects.create(name="Mugs")

    def test_slug_autogenerated_and_unique(self):
        a = Product.objects.create(name="Coffee Mug", category=self.cat, base_price=100)
        b = Product.objects.create(name="Coffee Mug", category=self.cat, base_price=100)
        self.assertEqual(a.slug, "coffee-mug")
        self.assertNotEqual(a.slug, b.slug)

    def test_sale_price_and_discount(self):
        p = Product.objects.create(name="Bottle", category=self.cat,
                                   base_price=Decimal("500"), sale_price=Decimal("400"))
        self.assertTrue(p.on_sale)
        self.assertEqual(p.price, Decimal("400"))
        self.assertEqual(p.discount_pct, 20)
