# Generated by Django 6.0.3 on 2026-06-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_design_json_order_design_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('kind', models.CharField(choices=[('bill', 'Bill / Invoice'), ('mockup', 'Mockup'), ('status', 'Status update')], default='bill', max_length=12)),
                ('body', models.TextField()),
                ('link', models.TextField(blank=True)),
                ('wa_link', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
